source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'bnuzgpa' do
pod 'Alamofire', '~> 4.6'
pod 'SwiftyJSON'
end
xcodeproj '/Users/zl/Documents/大三上/ios/ios大作业/北师小助手/bnuzgpa/bnuzgpa.xcodeproj'
